[phases.setup]
nixPkgs = ["...", "php83", "php83Extensions.zip", "php83Extensions.gd"]

[phases.install]
cmds = ["composer install --no-dev --ignore-platform-reqs"]

[start]
cmd = "php -S 0.0.0.0:$PORT"
